{% set name = "ada-py" %}
{% set version = "0.7.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Krande/adapy/archive/v{{ version }}.tar.gz
  sha256: 44bbd98b4abd1689c50dd4cd5fedcbc89080754b83b6a1109f7609e22f7202de

build:
  noarch: python
  script: python -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - ada-viewer=ada.visit.websocket_cli:ws_cli_app

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy
    - hdf5
    - h5py
    - ifcopenshell
    - bcf-client
    - pythonocc-core
    - python-gmsh
    - pyquaternion
    - trimesh
    - occt >=7.7.2
    - send2trash
    - meshio
    - websockets
    - plotly
    - python-kaleido
    - pydantic
    - ipywidgets
    - jupyterlab
    - pyparsing
    - pyglfw
    - pygfx
    - python-flatbuffers

test:
  source_files:
    - tests
    - files
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pytest-asyncio
    - calculix
  imports:
    - ada
  commands:
    - pytest tests --ignore=tests/fem --ignore=tests/profiling --ignore=tests/examples --ignore=tests/full/frontend --cov=ada --cov-report=xml --ignore=tests/core/visit/plotting/test_easy_plotly.py

about:
  home: https://github.com/krande/adapy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A python library for structural analysis and design"
  doc_url: https://krande.github.io/adapy/

extra:
  recipe-maintainers:
    - Krande
